[versions]
androidGradlePlugin = "8.0.1"
androidxActivity = "1.7.1"
androidxComposeBom = "2023.05.01"
androidxComposeCompiler = "1.4.7"
androidxCore = "1.10.1"
androidxLifecycle = "2.6.1"
androidxTestEspresso = "3.5.1"
androidxTestExt = "1.1.5"
gradleMavenPublish = "0.25.2"
junit = "4.13.2"
kotlin = "1.8.21"
ktlint = "0.48.2"
spotless = "6.18.0"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxTestEspresso" }
androidx-test-ext-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExt" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
gradle-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "gradleMavenPublish" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
